%% ACL — project isolation
%% sensor+nrf project: coap-server, nrf, sensor-device
%% vessel project: vessel (completely isolated)
{allow,{username,"coap-server"},all,["sensor/#","industrial/#"]}.
{allow,{username,"nrf"},all,["sensor/#","industrial/#"]}.
{allow,{username,"sensor-device"},all,["sensor/#"]}.
{allow,{username,"vessel"},all,["vessel/#"]}.
{allow,{ipaddr,"127.0.0.1"},all,["$SYS/#","#"]}.
{deny,all,subscribe,["$SYS/#",{eq,"#"},{eq,"+/#"}]}.
{deny,all}.
